[package]
name = "synthlauncher"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["backend", "frontend/src-tauri", "meta"]

[dependencies]
synthlauncher-backend = { path = "backend" }
tokio = "1.44.1"
clap = { version = "4.5.34", features = ["derive"] } 
