[package]
name = "synthlauncher-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
synthlauncher-interface = { path = "../interface" }
serde = { version = "1.0.219", features = ["derive"] }
anyhow = "1.0.97"
itertools = "0.14.0"
regex = "1.11.1"
which = "7.0.2"
lazy_static = "1.5.0"