[package]
name = "sl-skin"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] } 
