name: Build and Release SynthLauncher

on:
  push:
    tags:
      - "v*" # Trigger on version tags (e.g., v1.0.0)
  workflow_dispatch: # Allow manual triggering

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: linux-arm
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            artifact_name: linux-x64
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            artifact_name: macos-arm
            target: aarch64-apple-darwin
          - os: macos-latest
            artifact_name: macos-x64
            target: x86_64-apple-darwin
          - os: windows-latest
            artifact_name: windows-x64
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            artifact_name: windows-arm
            target: aarch64-pc-windows-msvc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          override: true

      - name: Build (Release)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Package binary
        shell: bash
        run: |
          mkdir -p release
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            cp target/${{ matrix.target }}/release/synthlauncher.exe release/
          else
            cp target/${{ matrix.target }}/release/synthlauncher release/
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: synth_launcher-${{ matrix.artifact_name }}
          path: release/

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: SynthLauncher ${{ github.ref_name }}
          body: |
            **SynthLauncher** ${{ github.ref_name }}
            - Built for Windows, macOS, and Linux
            - Commit: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
          draft: false
          prerelease: false
          files: |
            artifacts/synth_launcher-linux/synthlauncher
            artifacts/synth_launcher-macos/synthlauncher
            artifacts/synth_launcher-windows/synthlauncher.exe
